default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: mitchell
  password:

development:
  <<: *default
  database: great_reads_development

test:
  <<: *default
  database: great_reads_test
